# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

allowInsecureHttps: Optional[bool]
"""
Flag to set whether to allow https with invalid certificates
"""

apiToken: Optional[str]
"""
Netbox API authentication token
"""

headers: Optional[str]
"""
Set these header on all requests to Netbox
"""

serverUrl: Optional[str]
"""
Location of Netbox server including scheme and optional port
"""

skipVersionCheck: Optional[bool]
"""
If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
unsupported Netbox version. Also useful for local testing on terraform plans.
"""

