# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('netbox')


class _ExportableConfig(types.ModuleType):
    @property
    def allow_insecure_https(self) -> Optional[bool]:
        """
        Flag to set whether to allow https with invalid certificates
        """
        return __config__.get_bool('allowInsecureHttps')

    @property
    def api_token(self) -> Optional[str]:
        """
        Netbox API authentication token
        """
        return __config__.get('apiToken') or _utilities.get_env('NETBOX_API_TOKEN')

    @property
    def headers(self) -> Optional[str]:
        """
        Set these header on all requests to Netbox
        """
        return __config__.get('headers')

    @property
    def server_url(self) -> Optional[str]:
        """
        Location of Netbox server including scheme and optional port
        """
        return __config__.get('serverUrl') or _utilities.get_env('NETBOX_SERVER_URL')

    @property
    def skip_version_check(self) -> Optional[bool]:
        """
        If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
        unsupported Netbox version. Also useful for local testing on terraform plans.
        """
        return __config__.get_bool('skipVersionCheck')

