# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .aggregate import *
from .available_ip_address import *
from .available_prefix import *
from .circuit import *
from .circuit_provider import *
from .circuit_termination import *
from .circuit_type import *
from .cluster import *
from .cluster_group import *
from .cluster_type import *
from .custom_field import *
from .device import *
from .device_role import *
from .device_type import *
from .get_cluster import *
from .get_cluster_group import *
from .get_cluster_type import *
from .get_device_role import *
from .get_device_type import *
from .get_interfaces import *
from .get_ip_addresses import *
from .get_ip_range import *
from .get_platform import *
from .get_prefix import *
from .get_region import *
from .get_site import *
from .get_tag import *
from .get_tenant import *
from .get_tenant_group import *
from .get_tenants import *
from .get_virtual_machines import *
from .get_vlan import *
from .get_vrf import *
from .interface import *
from .ip_address import *
from .ip_range import *
from .ipam_role import *
from .manufacturer import *
from .platform import *
from .prefix import *
from .primary_ip import *
from .provider import *
from .region import *
from .rir import *
from .service import *
from .site import *
from .tag import *
from .tenant import *
from .tenant_group import *
from .token import *
from .user import *
from .virtual_machine import *
from .vlan import *
from .vrf import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_netbox.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_netbox.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "netbox",
  "mod": "index/aggregate",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/aggregate:Aggregate": "Aggregate"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/availableIpAddress",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/availableIpAddress:AvailableIpAddress": "AvailableIpAddress"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/availablePrefix",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/availablePrefix:AvailablePrefix": "AvailablePrefix"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/circuit",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/circuit:Circuit": "Circuit"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/circuitProvider",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/circuitProvider:CircuitProvider": "CircuitProvider"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/circuitTermination",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/circuitTermination:CircuitTermination": "CircuitTermination"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/circuitType",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/circuitType:CircuitType": "CircuitType"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/cluster",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/clusterGroup",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/clusterGroup:ClusterGroup": "ClusterGroup"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/clusterType",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/clusterType:ClusterType": "ClusterType"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/customField",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/customField:CustomField": "CustomField"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/device",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/device:Device": "Device"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/deviceRole",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/deviceRole:DeviceRole": "DeviceRole"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/deviceType",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/deviceType:DeviceType": "DeviceType"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/interface",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/interface:Interface": "Interface"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/ipAddress",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/ipAddress:IpAddress": "IpAddress"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/ipRange",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/ipRange:IpRange": "IpRange"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/ipamRole",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/ipamRole:IpamRole": "IpamRole"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/manufacturer",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/manufacturer:Manufacturer": "Manufacturer"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/platform",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/platform:Platform": "Platform"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/prefix",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/prefix:Prefix": "Prefix"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/primaryIp",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/primaryIp:PrimaryIp": "PrimaryIp"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/region",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/region:Region": "Region"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/rir",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/rir:Rir": "Rir"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/service",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/service:Service": "Service"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/site",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/site:Site": "Site"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/tag",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/tag:Tag": "Tag"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/tenant",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/tenant:Tenant": "Tenant"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/tenantGroup",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/tenantGroup:TenantGroup": "TenantGroup"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/token",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/token:Token": "Token"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/user",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/user:User": "User"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/virtualMachine",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/virtualMachine:VirtualMachine": "VirtualMachine"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/vlan",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/vlan:Vlan": "Vlan"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/vrf",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/vrf:Vrf": "Vrf"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "netbox",
  "token": "pulumi:providers:netbox",
  "fqn": "pulumi_netbox",
  "class": "Provider"
 }
]
"""
)
