# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetClusterTypeResult',
    'AwaitableGetClusterTypeResult',
    'get_cluster_type',
    'get_cluster_type_output',
]

@pulumi.output_type
class GetClusterTypeResult:
    """
    A collection of values returned by getClusterType.
    """
    def __init__(__self__, cluster_type_id=None, id=None, name=None):
        if cluster_type_id and not isinstance(cluster_type_id, int):
            raise TypeError("Expected argument 'cluster_type_id' to be a int")
        pulumi.set(__self__, "cluster_type_id", cluster_type_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="clusterTypeId")
    def cluster_type_id(self) -> int:
        return pulumi.get(self, "cluster_type_id")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")


class AwaitableGetClusterTypeResult(GetClusterTypeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetClusterTypeResult(
            cluster_type_id=self.cluster_type_id,
            id=self.id,
            name=self.name)


def get_cluster_type(name: Optional[str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetClusterTypeResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbox:index/getClusterType:getClusterType', __args__, opts=opts, typ=GetClusterTypeResult).value

    return AwaitableGetClusterTypeResult(
        cluster_type_id=__ret__.cluster_type_id,
        id=__ret__.id,
        name=__ret__.name)


@_utilities.lift_output_func(get_cluster_type)
def get_cluster_type_output(name: Optional[pulumi.Input[str]] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetClusterTypeResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
